site_name: Recipes around the Web
plugins:
  - search
theme:
  name: material
  logo: images/logo-cutout.png
  favicon: images/logo-cutout.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: cyan
  features:
    - navigation.top
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TimyStream
copyright: Built and put together with ❤️ by Timy Stream & Friends & Contributors
repo_url: https://github.com/TimyStream/recipes-around-the-web
repo_name: TimyStream/recipes-around-the-web
